name: github-actions
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.0"

      - name: make lint
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/app -w /app golangci/golangci-lint:v1.50 golangci-lint run -v

      - name: Make tests
        run: go test -v ./...

